version: "3.7"
volumes:
  postgredata:
    external: false
services:
    # redis:
    #   image: redis:5.0.6-alpine
    #   restart: always
    #   ports:
    #     - 6379:6379
    
    postgres:
        image: postgres:11.3-alpine
        restart: always
        environment:
          - POSTGexxRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
        ports:
          - 5432:5432
        volumes:
          - postgredata:/var/lib/postgresql/data